version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6565
      - POSTGRES_DB=estates_alpes_real_estate

volumes:
  postgres-data:
